# uncomment the next line to test locally
# local_backend: true
publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
media_folder: public/images/uploads
public_folder: /images/uploads
site_url: https://nexusvida.com
show_preview_links: false
collections:
  - name: continents
    label: Continents
    label_singular: Continent
    folder: _content/continents
    preview_path: continents/{{slug}}
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
  - name: countries
    label: Countries
    label_singular: Country
    folder: _content/countries
    preview_path: countries/{{slug}}
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Icon, name: icon, widget: string }
      - label: Continent
        name: continent
        widget: relation
        collection: continents
        search_fields: [title]
        value_field: '{{slug}}'
        display_fields: ['{{title}}']
      - label: Data
        name: data
        widget: object
        collapse: true
        fields:
          - { label: Global Peace Index, name: global-peace-index, widget: number, required: false }
          - { label: Gross Domestic Product, name: gross-domestic-product, widget: number, required: false }
          - { label: Human Development Index, name: human-development-index, widget: number, required: false }
          - { label: World Happiness Report, name: world-happiness-report, widget: number, required: false }
          - { label: Cost of Living, name: cost-of-living, widget: number, required: false }
          - { label: Good Country Index, name: good-country-index, widget: number, required: false }
          - { label: Global Freedom Score, name: global-freedom-score, widget: number, required: false }
          - { label: Democracy Index, name: democracy-index, widget: number, required: false }
      - { label: Body, name: body, widget: markdown }
  - name: datasets
    label: Datasets
    label_singular: Dataset
    folder: _content/datasets
    preview_path: datasets/{{slug}}
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Source, name: source, widget: string }
      - label: Year
        name: year
        widget: number
        min: 4
        max: 4
      - label: Date Added
        name: added
        widget: datetime
        format: YYYY-MM-DD
        date_format: YYYY-MM-DD
      - label: Date Updated
        name: updated
        widget: datetime
        format: YYYY-MM-DD
        date_format: YYYY-MM-DD
        required: false
      - { label: Link, name: url, widget: string }
      - label: Adjustments
        name: adjustments
        widget: object
        collapse: true
        required: false
        fields:
          - label: Excluded
            name: excluded
            widget: list
            required: false
            field: { label: Rank, name: rank, widget: number }
      - { label: Body, name: body, widget: markdown }

